steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.']
images:
- 'gcr.io/$PROJECT_ID/firebase'
tags: ['cloud-builders-community']





# Image already pushed - Reference this runner image with the following URL = gcr.io/$PROJECT_ID/firebase  $PROJECT_ID=coffee-and-feel

# RUN gcloud builds submit DOCKERFILE_SOURCE_PATH --config CLOUDBUILD_YAML_SOURCE_PATH --project GCLOUD_PROJECT_ID