  steps:
  - name: "gcr.io/$PROJECT_ID/pnpm:latest"
    entrypoint: pnpm
    args: ['install']
    id: install
    
  - name: "gcr.io/$PROJECT_ID/pnpm:latest"
    entrypoint: nx
    args: ['run', 'admin:build']
    id: build
    waitFor: ['install']
    env: [CYPRESS_INSTALL_BINARY=0]

  - name: "gcr.io/$PROJECT_ID/pnpm:latest"
    entrypoint: bash
    args: [ "-c", "cp ci/.firebase/production/admin/firebase.json ."]
    waitFor:
      - build

  - name: "gcr.io/$PROJECT_ID/pnpm:latest"
    entrypoint: bash
    args: ["-c", "cp ci/.firebase/production/admin/.firebaserc ."]
    waitFor:
      - build

  - name: "gcr.io/$PROJECT_ID/pnpm:latest"
    entrypoint: bash
    args: ["-c", 'cd dist/apps/admin', "ls -la"]
    waitFor:
      - build

  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project=coffee-and-feel", "--only=hosting"]
    waitFor:
      - build
