steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pnpm",  "."]
  
  # Deploy image

  - name: "gcr.io/cloud-builders/docker"
    args: ['push', "gcr.io/$PROJECT_ID/pnpm"]


tags: ['runner']


# RUN gcloud builds submit DOCKERFILE_SOURCE_PATH --config CLOUDBUILD_YAML_SOURCE_PATH --project GCLOUD_PROJECT_ID