steps:
  # Pull cached image from last run
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/front-dev:latest || exit 0']

  # Build image from cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/front-dev:latest',
        '--cache-from',
        'gcr.io/$PROJECT_ID/front-dev:latest',
        "-f",
        "./ci/development/frontend/Dockerfile",
        '.',
      ]

  # Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/front-dev:latest']


  # Deploy pushed image to Cloud Run using gcloud cli
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'store-dev',
        '--image',
        'gcr.io/$PROJECT_ID/front-dev',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]
      
timeout: 1800s
