steps:
  # Pull cached image from last run
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/front:latest || exit 0']

  # Build image from cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/front:latest',
        '--cache-from',
        'gcr.io/$PROJECT_ID/front:latest',
        '.',
      ]

  # Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/front:latest']

  # Deploy pushed image to Cloud Run using gcloud cli
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'coffee-and-feel',
        '--image',
        'gcr.io/$PROJECT_ID/front',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

timeout: 1800s
