steps:
  # Pull cached image from last run
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/admin-dev:latest || exit 0']

  # Decrypt key
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      [
        '-c',
        'gcloud kms decrypt --ciphertext-file=.env.enc --plaintext-file=.env --location=global --keyring=cloudbuild-env --key=cloudbuild-env',
      ]

  #Build image from cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/admin-dev:latest',
        '--cache-from',
        'gcr.io/$PROJECT_ID/admin-dev:latest',
        '-f',
        './ci/development/admin/Dockerfile',
        '.',
      ]

  # Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/admin-dev:latest']

timeout: 1800s
